<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TasksTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('tasks')->insert([
            // Tasks for User 1
            [
                'title' => 'Complete project report',
                'description' => 'Finish the final report for the project and submit it to the manager.',
                'status' => 'pending',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Prepare presentation',
                'description' => 'Create slides for the upcoming presentation.',
                'status' => 'completed',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Update website',
                'description' => 'Make necessary updates to the company website.',
                'status' => 'pending',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Organize team meeting',
                'description' => 'Schedule and organize a team meeting for project discussion.',
                'status' => 'completed',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Review code',
                'description' => 'Review the code submitted by the development team.',
                'status' => 'pending',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Write documentation',
                'description' => 'Write the documentation for the new software module.',
                'status' => 'completed',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Fix bugs',
                'description' => 'Identify and fix bugs in the application.',
                'status' => 'pending',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Deploy application',
                'description' => 'Deploy the application to the production server.',
                'status' => 'completed',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Conduct training',
                'description' => 'Conduct training sessions for new employees.',
                'status' => 'pending',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Update user guide',
                'description' => 'Update the user guide with the latest features.',
                'status' => 'completed',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Tasks for User 2
            [
                'title' => 'Design new logo',
                'description' => 'Create a new logo for the company.',
                'status' => 'pending',
                'user_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Market research',
                'description' => 'Conduct market research for the new product.',
                'status' => 'completed',
                'user_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Client meeting',
                'description' => 'Attend a meeting with the client to discuss project requirements.',
                'status' => 'pending',
                'user_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Prepare budget',
                'description' => 'Prepare the budget for the upcoming quarter.',
                'status' => 'completed',
                'user_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Write blog post',
                'description' => 'Write a blog post about the latest industry trends.',
                'status' => 'pending',
                'user_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Update social media',
                'description' => 'Update the company’s social media profiles with new content.',
                'status' => 'completed',
                'user_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Create marketing plan',
                'description' => 'Develop a marketing plan for the new product launch.',
                'status' => 'pending',
                'user_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Analyze sales data',
                'description' => 'Analyze the sales data from the last quarter.',
                'status' => 'completed',
                'user_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Customer feedback',
                'description' => 'Collect and analyze customer feedback.',
                'status' => 'pending',
                'user_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Plan event',
                'description' => 'Plan the company’s annual event.',
                'status' => 'completed',
                'user_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Tasks for User 3
            [
                'title' => 'Develop new feature',
                'description' => 'Develop a new feature for the application.',
                'status' => 'pending',
                'user_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Test application',
                'description' => 'Test the application for bugs and issues.',
                'status' => 'completed',
                'user_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Optimize database',
                'description' => 'Optimize the database for better performance.',
                'status' => 'pending',
                'user_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Refactor code',
                'description' => 'Refactor the existing codebase to improve readability.',
                'status' => 'completed',
                'user_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Update API',
                'description' => 'Update the API to include new endpoints.',
                'status' => 'pending',
                'user_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Write unit tests',
                'description' => 'Write unit tests for the new feature.',
                'status' => 'completed',
                'user_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Deploy updates',
                'description' => 'Deploy the latest updates to the production server.',
                'status' => 'pending',
                'user_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Monitor server',
                'description' => 'Monitor the server for any issues.',
                'status' => 'completed',
                'user_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Create backup',
                'description' => 'Create a backup of the database.',
                'status' => 'pending',
                'user_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Update dependencies',
                'description' => 'Update the project dependencies to the latest versions.',
                'status' => 'completed',
                'user_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Fix security issues',
                'description' => 'Identify and fix security vulnerabilities.',
                'status' => 'pending',
                'user_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Improve UI',
                'description' => 'Improve the user interface of the application.',
                'status' => 'completed',
                'user_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Conduct code review',
                'description' => 'Conduct a code review for the new feature.',
                'status' => 'pending',
                'user_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Document API',
                'description' => 'Document the API endpoints and usage.',
                'status' => 'completed',
                'user_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Set up CI/CD',
                'description' => 'Set up continuous integration and continuous deployment.',
                'status' => 'pending',
                'user_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}